///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestWeb.REC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddAccountError recording.
    /// </summary>
    [TestModule("5a9f5b86-947f-4e3c-b21c-c120c2a76764", ModuleType.Recording, 1)]
    public partial class AddAccountError : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::TestWeb.TestWebRepository repository.
        /// </summary>
        public static global::TestWeb.TestWebRepository repo = global::TestWeb.TestWebRepository.Instance;

        static AddAccountError instance = new AddAccountError();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddAccountError()
        {
            newUrl = "youtube.com";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddAccountError Instance
        {
            get { return instance; }
        }

#region Variables

        string _newUrl;

        /// <summary>
        /// Gets or sets the value of variable newUrl.
        /// </summary>
        [TestVariable("c8b3d45c-bb6d-476c-9590-82e192073d11")]
        public string newUrl
        {
            get { return _newUrl; }
            set { _newUrl = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HomePage.BtnSignIn' at 28;19.", repo.ApplicationUnderTest.HomePage.BtnSignInInfo, new RecordItemIndex(0));
            //repo.ApplicationUnderTest.HomePage.BtnSignIn.Click("28;19");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AuthenticationPage.InputEmailAddressLeft' at 150;10.", repo.ApplicationUnderTest.AuthenticationPage.InputEmailAddressLeftInfo, new RecordItemIndex(1));
            //repo.ApplicationUnderTest.AuthenticationPage.InputEmailAddressLeft.Click("150;10");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'black@#!@@gmail.com' with focus on 'ApplicationUnderTest.AuthenticationPage.InputEmailAddressLeft'.", repo.ApplicationUnderTest.AuthenticationPage.InputEmailAddressLeftInfo, new RecordItemIndex(2));
            //repo.ApplicationUnderTest.AuthenticationPage.InputEmailAddressLeft.PressKeys("black@#!@@gmail.com");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AuthenticationPage.BtnCreateAccount' at 56;25.", repo.ApplicationUnderTest.AuthenticationPage.BtnCreateAccountInfo, new RecordItemIndex(3));
            //repo.ApplicationUnderTest.AuthenticationPage.BtnCreateAccount.Click("56;25");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Invalid email address.') on item 'ApplicationUnderTest.AuthenticationPage.InvalidEmailMessage'.", repo.ApplicationUnderTest.AuthenticationPage.InvalidEmailMessageInfo, new RecordItemIndex(4));
            //Validate.AttributeEqual(repo.ApplicationUnderTest.AuthenticationPage.InvalidEmailMessageInfo, "InnerText", "Invalid email address.");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site URL in variable $newUrl with browser 'Chrome' in normal mode.", new RecordItemIndex(5));
            Host.Current.OpenBrowser(newUrl, "Chrome", "", false, false, false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
