///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestWeb.REC
{
    public partial class BuyProductContainNameInput
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void BuyProductContaineNameInput(RepoItemInfo addCartRepo, RepoItemInfo btnContinueRepo, string nameProduct)
        {
        	
        	string nameProductXPath = "/dom[@domain='automationpractice.com']//ul[#'homefeatured']//div[@class='right-block']//a[@title~'<title>']".Replace("<title>", nameProduct);
        	IList<Ranorex.ATag> listName = Host.Local.Find<Ranorex.ATag>(nameProductXPath);
        	
        	foreach (Ranorex.ATag product in listName) {
				product.MoveTo();
        	    Ranorex.Unknown addCartAdapter = addCartRepo.CreateAdapter<Ranorex.Unknown>(true);
    		    addCartAdapter.Click();
			    Ranorex.Unknown btnContinueInfoAdapter = btnContinueRepo.FindAdapter<Ranorex.Unknown>();
			    btnContinueInfoAdapter.Click();
        	}
        }

    }
}
