///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestWeb.REC
{
    public partial class BuySale
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        
        public void SelectProductSale(RepoItemInfo listItemSale, RepoItemInfo cartRepo, RepoItemInfo btnContinueRepo)
        {
        	IList<Ranorex.Unknown> listSaleItem = listItemSale.CreateAdapters<Ranorex.Unknown>();
        	
//        	Chọn 1 phần tử trong list để run
//        	for (int i = 0; i < 1; i++) {
//        		listSaleItem[i].MoveTo();
//        		Ranorex.Unknown cartAdapter = cartRepo.CreateAdapter<Ranorex.Unknown>(true);
//        		cartAdapter.Click();
//				Ranorex.Unknown btnContinueInfoAdapter = btnContinueRepo.FindAdapter<Ranorex.Unknown>();
//				btnContinueInfoAdapter.Click();
//        	}

        	foreach(Ranorex.Unknown itemSale in listSaleItem) 
        	{
        		itemSale.MoveTo();
        		Ranorex.Unknown cartAdapter = cartRepo.CreateAdapter<Ranorex.Unknown>(true);
        		cartAdapter.Click();
				Ranorex.Unknown btnContinueInfoAdapter = btnContinueRepo.FindAdapter<Ranorex.Unknown>();
				btnContinueInfoAdapter.Click();
        	}
        }
    }
}
