///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestWeb.REC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ProceedBuyer recording.
    /// </summary>
    [TestModule("dcf72899-0a43-4ea7-a941-74fe0c1b8f9c", ModuleType.Recording, 1)]
    public partial class ProceedBuyer : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::TestWeb.TestWebRepository repository.
        /// </summary>
        public static global::TestWeb.TestWebRepository repo = global::TestWeb.TestWebRepository.Instance;

        static ProceedBuyer instance = new ProceedBuyer();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ProceedBuyer()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ProceedBuyer Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ApplicationUnderTest.ShoppingCardSumary.ItemSelect.HoverCart' at Center.", repo.ApplicationUnderTest.ShoppingCardSumary.ItemSelect.HoverCartInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.ShoppingCardSumary.ItemSelect.HoverCart.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ShoppingCardSumary.SpanTagCheckOut' at Center.", repo.ApplicationUnderTest.ShoppingCardSumary.SpanTagCheckOutInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.ShoppingCardSumary.SpanTagCheckOut.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ShoppingCardSumary.CenterColumn.ProceedToCheckout' at Center.", repo.ApplicationUnderTest.ShoppingCardSumary.CenterColumn.ProceedToCheckoutInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.ShoppingCardSumary.CenterColumn.ProceedToCheckout.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'None' with focus on 'ApplicationUnderTest.ShoppingCardSumary.TextAreaAddComment'.", repo.ApplicationUnderTest.ShoppingCardSumary.TextAreaAddCommentInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.ShoppingCardSumary.TextAreaAddComment.PressKeys("None");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ShoppingCardSumary.CenterColumn.ProceedToCheckout' at Center.", repo.ApplicationUnderTest.ShoppingCardSumary.CenterColumn.ProceedToCheckoutInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.ShoppingCardSumary.CenterColumn.ProceedToCheckout.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ShoppingCardSumary.InputTagCgv' at Center.", repo.ApplicationUnderTest.ShoppingCardSumary.InputTagCgvInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.ShoppingCardSumary.InputTagCgv.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ShoppingCardSumary.CenterColumn.ProceedToCheckout' at Center.", repo.ApplicationUnderTest.ShoppingCardSumary.CenterColumn.ProceedToCheckoutInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.ShoppingCardSumary.CenterColumn.ProceedToCheckout.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ShoppingCardSumary.CenterColumn.PayByCheck' at Center.", repo.ApplicationUnderTest.ShoppingCardSumary.CenterColumn.PayByCheckInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.ShoppingCardSumary.CenterColumn.PayByCheck.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ShoppingCardSumary.IConfirmMyOrder' at Center.", repo.ApplicationUnderTest.ShoppingCardSumary.IConfirmMyOrderInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.ShoppingCardSumary.IConfirmMyOrder.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Your order on My Store is complete.') on item 'ApplicationUnderTest.ShoppingCardSumary.CenterColumn.YourOrderOnMyStoreIsComplete'.", repo.ApplicationUnderTest.ShoppingCardSumary.CenterColumn.YourOrderOnMyStoreIsCompleteInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.ApplicationUnderTest.ShoppingCardSumary.CenterColumn.YourOrderOnMyStoreIsCompleteInfo, "InnerText", "Your order on My Store is complete.");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
