///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestWeb.REC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SignInTestEmail recording.
    /// </summary>
    [TestModule("aa746f95-ed45-4d8f-b3c2-959ac7521e48", ModuleType.Recording, 1)]
    public partial class SignInTestEmail : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::TestWeb.TestWebRepository repository.
        /// </summary>
        public static global::TestWeb.TestWebRepository repo = global::TestWeb.TestWebRepository.Instance;

        static SignInTestEmail instance = new SignInTestEmail();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SignInTestEmail()
        {
            DumpEmail = "abc123";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SignInTestEmail Instance
        {
            get { return instance; }
        }

#region Variables

        string _DumpEmail;

        /// <summary>
        /// Gets or sets the value of variable DumpEmail.
        /// </summary>
        [TestVariable("a2063421-d4ac-49d2-97e7-da1c7a9fcfd8")]
        public string DumpEmail
        {
            get { return _DumpEmail; }
            set { _DumpEmail = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$DumpEmail' with focus on 'ApplicationUnderTest.AuthenticationPage.InputEmailAddressLeft'.", repo.ApplicationUnderTest.AuthenticationPage.InputEmailAddressLeftInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.AuthenticationPage.InputEmailAddressLeft.PressKeys(DumpEmail);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
