///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestWeb
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestWebRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d97f7e89-6c92-4586-9704-5a2808fe78ac")]
    public partial class TestWebRepository : RepoGenBaseFolder
    {
        static TestWebRepository instance = new TestWebRepository();
        TestWebRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        TestWebRepositoryFolders.LoginMyStoreGoogleChromeAppFolder _loginmystoregooglechrome;
        TestWebRepositoryFolders.OpenAppFolder _open;
        TestWebRepositoryFolders.ContactUsMyStoreGoogleChromeAppFolder _contactusmystoregooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the TestWebRepository element repository.
        /// </summary>
        [RepositoryFolder("d97f7e89-6c92-4586-9704-5a2808fe78ac")]
        public static TestWebRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestWebRepository() 
            : base("TestWebRepository", "/", null, 0, false, "d97f7e89-6c92-4586-9704-5a2808fe78ac", ".\\RepositoryImages\\TestWebRepositoryd97f7e89.rximgres")
        {
            _applicationundertest = new TestWebRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _loginmystoregooglechrome = new TestWebRepositoryFolders.LoginMyStoreGoogleChromeAppFolder(this);
            _open = new TestWebRepositoryFolders.OpenAppFolder(this);
            _contactusmystoregooglechrome = new TestWebRepositoryFolders.ContactUsMyStoreGoogleChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d97f7e89-6c92-4586-9704-5a2808fe78ac")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("020621a7-8b8b-4acf-bc5a-1f6435f61c25")]
        public virtual TestWebRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The LoginMyStoreGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("5dedd440-8a4d-4db6-ae63-bf12bcda4d37")]
        public virtual TestWebRepositoryFolders.LoginMyStoreGoogleChromeAppFolder LoginMyStoreGoogleChrome
        {
            get { return _loginmystoregooglechrome; }
        }

        /// <summary>
        /// The Open folder.
        /// </summary>
        [RepositoryFolder("d6037ea3-3243-45a3-b837-8375fedc91e1")]
        public virtual TestWebRepositoryFolders.OpenAppFolder Open
        {
            get { return _open; }
        }

        /// <summary>
        /// The ContactUsMyStoreGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("8f9b8f13-5444-4b6d-bb44-5c598cd41f42")]
        public virtual TestWebRepositoryFolders.ContactUsMyStoreGoogleChromeAppFolder ContactUsMyStoreGoogleChrome
        {
            get { return _contactusmystoregooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TestWebRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("020621a7-8b8b-4acf-bc5a-1f6435f61c25")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            TestWebRepositoryFolders.HomePageFolder _homepage;
            TestWebRepositoryFolders.AuthenticationPageFolder _authenticationpage;
            TestWebRepositoryFolders.ContactUsPageFolder _contactuspage;
            TestWebRepositoryFolders.ShoppingCardSumaryFolder _shoppingcardsumary;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='automationpractice.com']", parentFolder, 30000, null, false, "020621a7-8b8b-4acf-bc5a-1f6435f61c25", "")
            {
                _homepage = new TestWebRepositoryFolders.HomePageFolder(this);
                _authenticationpage = new TestWebRepositoryFolders.AuthenticationPageFolder(this);
                _contactuspage = new TestWebRepositoryFolders.ContactUsPageFolder(this);
                _shoppingcardsumary = new TestWebRepositoryFolders.ShoppingCardSumaryFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("020621a7-8b8b-4acf-bc5a-1f6435f61c25")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("020621a7-8b8b-4acf-bc5a-1f6435f61c25")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HomePage folder.
            /// </summary>
            [RepositoryFolder("7955d8ef-a3cb-404d-a4b9-4cfdc565bf8d")]
            public virtual TestWebRepositoryFolders.HomePageFolder HomePage
            {
                get { return _homepage; }
            }

            /// <summary>
            /// The AuthenticationPage folder.
            /// </summary>
            [RepositoryFolder("e2d67cce-7728-4362-ab8b-57b406508135")]
            public virtual TestWebRepositoryFolders.AuthenticationPageFolder AuthenticationPage
            {
                get { return _authenticationpage; }
            }

            /// <summary>
            /// The ContactUsPage folder.
            /// </summary>
            [RepositoryFolder("a6b7c68b-5639-4431-a490-b345c5e3443b")]
            public virtual TestWebRepositoryFolders.ContactUsPageFolder ContactUsPage
            {
                get { return _contactuspage; }
            }

            /// <summary>
            /// The ShoppingCardSumary folder.
            /// </summary>
            [RepositoryFolder("6724994c-4adf-4412-b258-7307e31d4079")]
            public virtual TestWebRepositoryFolders.ShoppingCardSumaryFolder ShoppingCardSumary
            {
                get { return _shoppingcardsumary; }
            }
        }

        /// <summary>
        /// The HomePageFolder folder.
        /// </summary>
        [RepositoryFolder("7955d8ef-a3cb-404d-a4b9-4cfdc565bf8d")]
        public partial class HomePageFolder : RepoGenBaseFolder
        {
            TestWebRepositoryFolders.SearchFolder _search;
            RepoItemInfo _btnsigninInfo;

            /// <summary>
            /// Creates a new HomePage  folder.
            /// </summary>
            public HomePageFolder(RepoGenBaseFolder parentFolder) :
                    base("HomePage", "", parentFolder, 0, null, false, "7955d8ef-a3cb-404d-a4b9-4cfdc565bf8d", "")
            {
                _search = new TestWebRepositoryFolders.SearchFolder(this);
                _btnsigninInfo = new RepoItemInfo(this, "BtnSignIn", ".//?/a[@innertext='Sign in']", "element", 30000, null, "c0a6bad1-0b88-4de8-a14c-35b80bb5735e");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7955d8ef-a3cb-404d-a4b9-4cfdc565bf8d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnSignIn item.
            /// </summary>
            [RepositoryItem("c0a6bad1-0b88-4de8-a14c-35b80bb5735e")]
            public virtual Ranorex.ATag BtnSignIn
            {
                get
                {
                    return _btnsigninInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BtnSignIn item info.
            /// </summary>
            [RepositoryItemInfo("c0a6bad1-0b88-4de8-a14c-35b80bb5735e")]
            public virtual RepoItemInfo BtnSignInInfo
            {
                get
                {
                    return _btnsigninInfo;
                }
            }

            /// <summary>
            /// The Search folder.
            /// </summary>
            [RepositoryFolder("4c34efec-5ccc-42fa-ad1e-319c9b2fec5f")]
            public virtual TestWebRepositoryFolders.SearchFolder Search
            {
                get { return _search; }
            }
        }

        /// <summary>
        /// The SearchFolder folder.
        /// </summary>
        [RepositoryFolder("4c34efec-5ccc-42fa-ad1e-319c9b2fec5f")]
        public partial class SearchFolder : RepoGenBaseFolder
        {
            RepoItemInfo _searchquerytopInfo;
            RepoItemInfo _resultsearchInfo;

            /// <summary>
            /// Creates a new Search  folder.
            /// </summary>
            public SearchFolder(RepoGenBaseFolder parentFolder) :
                    base("Search", "", parentFolder, 0, null, false, "4c34efec-5ccc-42fa-ad1e-319c9b2fec5f", "")
            {
                _searchquerytopInfo = new RepoItemInfo(this, "SearchQueryTop", ".//input[#'search_query_top']", ".//input[#'search_query_top']", 30000, null, "d85b029b-075a-4f70-840e-18afead8a2ef");
                _resultsearchInfo = new RepoItemInfo(this, "ResultSearch", ".//div[@class='ac_results' and @style~'display: block']/ul/li", "element", 30000, null, "c3fbbad7-d5b6-4ced-85d1-859574a420f0");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4c34efec-5ccc-42fa-ad1e-319c9b2fec5f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SearchQueryTop item.
            /// </summary>
            [RepositoryItem("d85b029b-075a-4f70-840e-18afead8a2ef")]
            public virtual Ranorex.InputTag SearchQueryTop
            {
                get
                {
                    return _searchquerytopInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SearchQueryTop item info.
            /// </summary>
            [RepositoryItemInfo("d85b029b-075a-4f70-840e-18afead8a2ef")]
            public virtual RepoItemInfo SearchQueryTopInfo
            {
                get
                {
                    return _searchquerytopInfo;
                }
            }

            /// <summary>
            /// The ResultSearch item.
            /// </summary>
            [RepositoryItem("c3fbbad7-d5b6-4ced-85d1-859574a420f0")]
            public virtual Ranorex.LiTag ResultSearch
            {
                get
                {
                    return _resultsearchInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The ResultSearch item info.
            /// </summary>
            [RepositoryItemInfo("c3fbbad7-d5b6-4ced-85d1-859574a420f0")]
            public virtual RepoItemInfo ResultSearchInfo
            {
                get
                {
                    return _resultsearchInfo;
                }
            }
        }

        /// <summary>
        /// The AuthenticationPageFolder folder.
        /// </summary>
        [RepositoryFolder("e2d67cce-7728-4362-ab8b-57b406508135")]
        public partial class AuthenticationPageFolder : RepoGenBaseFolder
        {
            TestWebRepositoryFolders.PersonalInfoFolder _personalinfo;
            RepoItemInfo _inputemailaddressleftInfo;
            RepoItemInfo _btncreateaccountInfo;
            RepoItemInfo _invalidemailmessageInfo;

            /// <summary>
            /// Creates a new AuthenticationPage  folder.
            /// </summary>
            public AuthenticationPageFolder(RepoGenBaseFolder parentFolder) :
                    base("AuthenticationPage", "", parentFolder, 0, null, false, "e2d67cce-7728-4362-ab8b-57b406508135", "")
            {
                _personalinfo = new TestWebRepositoryFolders.PersonalInfoFolder(this);
                _inputemailaddressleftInfo = new RepoItemInfo(this, "InputEmailAddressLeft", ".//input[#'email_create']", "element", 30000, null, "49bb5038-bd7f-4e33-baf0-5c2bf920fd61");
                _btncreateaccountInfo = new RepoItemInfo(this, "BtnCreateAccount", ".//button[#'SubmitCreate']", "element", 30000, null, "5b94ac31-6bda-459c-b663-ec0f4ca5f3d1");
                _invalidemailmessageInfo = new RepoItemInfo(this, "InvalidEmailMessage", ".//?/li[@innertext='Invalid email address.']", "element", 30000, null, "b98f52ea-9934-4488-8d02-c29392d52ae7");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e2d67cce-7728-4362-ab8b-57b406508135")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InputEmailAddressLeft item.
            /// </summary>
            [RepositoryItem("49bb5038-bd7f-4e33-baf0-5c2bf920fd61")]
            public virtual Ranorex.InputTag InputEmailAddressLeft
            {
                get
                {
                    return _inputemailaddressleftInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputEmailAddressLeft item info.
            /// </summary>
            [RepositoryItemInfo("49bb5038-bd7f-4e33-baf0-5c2bf920fd61")]
            public virtual RepoItemInfo InputEmailAddressLeftInfo
            {
                get
                {
                    return _inputemailaddressleftInfo;
                }
            }

            /// <summary>
            /// The BtnCreateAccount item.
            /// </summary>
            [RepositoryItem("5b94ac31-6bda-459c-b663-ec0f4ca5f3d1")]
            public virtual Ranorex.Button BtnCreateAccount
            {
                get
                {
                    return _btncreateaccountInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnCreateAccount item info.
            /// </summary>
            [RepositoryItemInfo("5b94ac31-6bda-459c-b663-ec0f4ca5f3d1")]
            public virtual RepoItemInfo BtnCreateAccountInfo
            {
                get
                {
                    return _btncreateaccountInfo;
                }
            }

            /// <summary>
            /// The InvalidEmailMessage item.
            /// </summary>
            [RepositoryItem("b98f52ea-9934-4488-8d02-c29392d52ae7")]
            public virtual Ranorex.LiTag InvalidEmailMessage
            {
                get
                {
                    return _invalidemailmessageInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The InvalidEmailMessage item info.
            /// </summary>
            [RepositoryItemInfo("b98f52ea-9934-4488-8d02-c29392d52ae7")]
            public virtual RepoItemInfo InvalidEmailMessageInfo
            {
                get
                {
                    return _invalidemailmessageInfo;
                }
            }

            /// <summary>
            /// The PersonalInfo folder.
            /// </summary>
            [RepositoryFolder("b436dcd8-e642-4eba-b44a-c553b9fd9974")]
            public virtual TestWebRepositoryFolders.PersonalInfoFolder PersonalInfo
            {
                get { return _personalinfo; }
            }
        }

        /// <summary>
        /// The PersonalInfoFolder folder.
        /// </summary>
        [RepositoryFolder("b436dcd8-e642-4eba-b44a-c553b9fd9974")]
        public partial class PersonalInfoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _radiotitleInfo;
            RepoItemInfo _inputfirstnameInfo;
            RepoItemInfo _inputlastnameInfo;
            RepoItemInfo _inputpasswordInfo;
            RepoItemInfo _selectdayInfo;
            RepoItemInfo _selectmonthInfo;
            RepoItemInfo _selectyearInfo;
            RepoItemInfo _inputcompanyInfo;
            RepoItemInfo _inputaddress1Info;
            RepoItemInfo _inputaddress2Info;
            RepoItemInfo _inputcityInfo;
            RepoItemInfo _selectstateInfo;
            RepoItemInfo _inputzipcodeInfo;
            RepoItemInfo _selectcountryInfo;
            RepoItemInfo _textareaaddinfoInfo;
            RepoItemInfo _inputmobilephoneInfo;
            RepoItemInfo _inputaddressaliasInfo;
            RepoItemInfo _btnregisterInfo;

            /// <summary>
            /// Creates a new PersonalInfo  folder.
            /// </summary>
            public PersonalInfoFolder(RepoGenBaseFolder parentFolder) :
                    base("PersonalInfo", "", parentFolder, 0, null, false, "b436dcd8-e642-4eba-b44a-c553b9fd9974", "")
            {
                _radiotitleInfo = new RepoItemInfo(this, "RadioTitle", ".//?/label[@innertext='Mr.']", "element", 30000, null, "3f0b8519-4508-4167-9dab-46359d203701");
                _inputfirstnameInfo = new RepoItemInfo(this, "InputFirstName", ".//input[#'customer_firstname']", "element", 30000, null, "df090f64-7e6a-429b-85cc-92bcd48bc0c9");
                _inputlastnameInfo = new RepoItemInfo(this, "InputLastName", ".//input[#'customer_lastname']", "element", 30000, null, "b109e696-b363-44ec-8dc3-7fd94a122376");
                _inputpasswordInfo = new RepoItemInfo(this, "InputPassword", ".//input[#'passwd']", "element", 30000, null, "bc6352ba-e255-4f5f-b75a-2ff0a276e135");
                _selectdayInfo = new RepoItemInfo(this, "SelectDay", ".//select[#'days']", "element", 30000, null, "862c8346-336a-4767-8bea-e4b7ea76b651");
                _selectmonthInfo = new RepoItemInfo(this, "SelectMonth", ".//select[#'months']", "element", 30000, null, "e302e002-3bf4-4802-9083-02c53dd93b36");
                _selectyearInfo = new RepoItemInfo(this, "SelectYear", ".//select[#'years']", "element", 30000, null, "ab7ffba5-3a6f-4fa0-9b6d-54f6211420b0");
                _inputcompanyInfo = new RepoItemInfo(this, "InputCompany", ".//input[#'company']", "element", 30000, null, "f7bc0ec1-52fd-4158-af9a-74949e33e5bd");
                _inputaddress1Info = new RepoItemInfo(this, "InputAddress1", ".///input[@name='address1']", "element", 30000, null, "0f1b2682-b695-4dbf-87b1-5d417eef06a2");
                _inputaddress2Info = new RepoItemInfo(this, "InputAddress2", ".///input[@name='address2']", "element", 30000, null, "e744d375-248a-4e22-b70d-1e1de644341d");
                _inputcityInfo = new RepoItemInfo(this, "InputCity", ".//input[#'city']", "element", 30000, null, "86e66105-ad63-4b09-b918-50b4e63c4bba");
                _selectstateInfo = new RepoItemInfo(this, "SelectState", ".//select[#'id_state']", "element", 30000, null, "d8865427-0efe-4563-b6fb-c792452a556a");
                _inputzipcodeInfo = new RepoItemInfo(this, "InputZipCode", ".//input[#'postcode']", "element", 30000, null, "14731b69-84c0-4136-b194-3f83c8481359");
                _selectcountryInfo = new RepoItemInfo(this, "SelectCountry", ".//select[#'id_country']", "element", 30000, null, "cb617fd3-ec9d-48e8-943b-8125280be813");
                _textareaaddinfoInfo = new RepoItemInfo(this, "TextAreaAddInfo", ".//textarea[#'other']", "element", 30000, null, "6f16e74b-de19-437e-9da0-de006703944e");
                _inputmobilephoneInfo = new RepoItemInfo(this, "InputMobilePhone", ".//input[#'phone_mobile']", "element", 30000, null, "c9e1052f-45c6-4b40-a5ed-1dbb550f3b5b");
                _inputaddressaliasInfo = new RepoItemInfo(this, "InputAddressAlias", ".//input[#'alias']", "element", 30000, null, "3b89129a-b7eb-48b0-b008-8f377540036b");
                _btnregisterInfo = new RepoItemInfo(this, "BtnRegister", ".//button[#'submitAccount']/span[@innertext='Register']", ".//button[#'submitAccount']/span[@innertext='Register']", 30000, null, "a0cd9497-07ab-404c-b2d4-a4c5e1b11d76");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b436dcd8-e642-4eba-b44a-c553b9fd9974")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RadioTitle item.
            /// </summary>
            [RepositoryItem("3f0b8519-4508-4167-9dab-46359d203701")]
            public virtual Ranorex.LabelTag RadioTitle
            {
                get
                {
                    return _radiotitleInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The RadioTitle item info.
            /// </summary>
            [RepositoryItemInfo("3f0b8519-4508-4167-9dab-46359d203701")]
            public virtual RepoItemInfo RadioTitleInfo
            {
                get
                {
                    return _radiotitleInfo;
                }
            }

            /// <summary>
            /// The InputFirstName item.
            /// </summary>
            [RepositoryItem("df090f64-7e6a-429b-85cc-92bcd48bc0c9")]
            public virtual Ranorex.InputTag InputFirstName
            {
                get
                {
                    return _inputfirstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputFirstName item info.
            /// </summary>
            [RepositoryItemInfo("df090f64-7e6a-429b-85cc-92bcd48bc0c9")]
            public virtual RepoItemInfo InputFirstNameInfo
            {
                get
                {
                    return _inputfirstnameInfo;
                }
            }

            /// <summary>
            /// The InputLastName item.
            /// </summary>
            [RepositoryItem("b109e696-b363-44ec-8dc3-7fd94a122376")]
            public virtual Ranorex.InputTag InputLastName
            {
                get
                {
                    return _inputlastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputLastName item info.
            /// </summary>
            [RepositoryItemInfo("b109e696-b363-44ec-8dc3-7fd94a122376")]
            public virtual RepoItemInfo InputLastNameInfo
            {
                get
                {
                    return _inputlastnameInfo;
                }
            }

            /// <summary>
            /// The InputPassword item.
            /// </summary>
            [RepositoryItem("bc6352ba-e255-4f5f-b75a-2ff0a276e135")]
            public virtual Ranorex.InputTag InputPassword
            {
                get
                {
                    return _inputpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputPassword item info.
            /// </summary>
            [RepositoryItemInfo("bc6352ba-e255-4f5f-b75a-2ff0a276e135")]
            public virtual RepoItemInfo InputPasswordInfo
            {
                get
                {
                    return _inputpasswordInfo;
                }
            }

            /// <summary>
            /// The SelectDay item.
            /// </summary>
            [RepositoryItem("862c8346-336a-4767-8bea-e4b7ea76b651")]
            public virtual Ranorex.SelectTag SelectDay
            {
                get
                {
                    return _selectdayInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SelectDay item info.
            /// </summary>
            [RepositoryItemInfo("862c8346-336a-4767-8bea-e4b7ea76b651")]
            public virtual RepoItemInfo SelectDayInfo
            {
                get
                {
                    return _selectdayInfo;
                }
            }

            /// <summary>
            /// The SelectMonth item.
            /// </summary>
            [RepositoryItem("e302e002-3bf4-4802-9083-02c53dd93b36")]
            public virtual Ranorex.SelectTag SelectMonth
            {
                get
                {
                    return _selectmonthInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SelectMonth item info.
            /// </summary>
            [RepositoryItemInfo("e302e002-3bf4-4802-9083-02c53dd93b36")]
            public virtual RepoItemInfo SelectMonthInfo
            {
                get
                {
                    return _selectmonthInfo;
                }
            }

            /// <summary>
            /// The SelectYear item.
            /// </summary>
            [RepositoryItem("ab7ffba5-3a6f-4fa0-9b6d-54f6211420b0")]
            public virtual Ranorex.SelectTag SelectYear
            {
                get
                {
                    return _selectyearInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SelectYear item info.
            /// </summary>
            [RepositoryItemInfo("ab7ffba5-3a6f-4fa0-9b6d-54f6211420b0")]
            public virtual RepoItemInfo SelectYearInfo
            {
                get
                {
                    return _selectyearInfo;
                }
            }

            /// <summary>
            /// The InputCompany item.
            /// </summary>
            [RepositoryItem("f7bc0ec1-52fd-4158-af9a-74949e33e5bd")]
            public virtual Ranorex.InputTag InputCompany
            {
                get
                {
                    return _inputcompanyInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputCompany item info.
            /// </summary>
            [RepositoryItemInfo("f7bc0ec1-52fd-4158-af9a-74949e33e5bd")]
            public virtual RepoItemInfo InputCompanyInfo
            {
                get
                {
                    return _inputcompanyInfo;
                }
            }

            /// <summary>
            /// The InputAddress1 item.
            /// </summary>
            [RepositoryItem("0f1b2682-b695-4dbf-87b1-5d417eef06a2")]
            public virtual Ranorex.InputTag InputAddress1
            {
                get
                {
                    return _inputaddress1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputAddress1 item info.
            /// </summary>
            [RepositoryItemInfo("0f1b2682-b695-4dbf-87b1-5d417eef06a2")]
            public virtual RepoItemInfo InputAddress1Info
            {
                get
                {
                    return _inputaddress1Info;
                }
            }

            /// <summary>
            /// The InputAddress2 item.
            /// </summary>
            [RepositoryItem("e744d375-248a-4e22-b70d-1e1de644341d")]
            public virtual Ranorex.InputTag InputAddress2
            {
                get
                {
                    return _inputaddress2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputAddress2 item info.
            /// </summary>
            [RepositoryItemInfo("e744d375-248a-4e22-b70d-1e1de644341d")]
            public virtual RepoItemInfo InputAddress2Info
            {
                get
                {
                    return _inputaddress2Info;
                }
            }

            /// <summary>
            /// The InputCity item.
            /// </summary>
            [RepositoryItem("86e66105-ad63-4b09-b918-50b4e63c4bba")]
            public virtual Ranorex.InputTag InputCity
            {
                get
                {
                    return _inputcityInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputCity item info.
            /// </summary>
            [RepositoryItemInfo("86e66105-ad63-4b09-b918-50b4e63c4bba")]
            public virtual RepoItemInfo InputCityInfo
            {
                get
                {
                    return _inputcityInfo;
                }
            }

            /// <summary>
            /// The SelectState item.
            /// </summary>
            [RepositoryItem("d8865427-0efe-4563-b6fb-c792452a556a")]
            public virtual Ranorex.SelectTag SelectState
            {
                get
                {
                    return _selectstateInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SelectState item info.
            /// </summary>
            [RepositoryItemInfo("d8865427-0efe-4563-b6fb-c792452a556a")]
            public virtual RepoItemInfo SelectStateInfo
            {
                get
                {
                    return _selectstateInfo;
                }
            }

            /// <summary>
            /// The InputZipCode item.
            /// </summary>
            [RepositoryItem("14731b69-84c0-4136-b194-3f83c8481359")]
            public virtual Ranorex.InputTag InputZipCode
            {
                get
                {
                    return _inputzipcodeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputZipCode item info.
            /// </summary>
            [RepositoryItemInfo("14731b69-84c0-4136-b194-3f83c8481359")]
            public virtual RepoItemInfo InputZipCodeInfo
            {
                get
                {
                    return _inputzipcodeInfo;
                }
            }

            /// <summary>
            /// The SelectCountry item.
            /// </summary>
            [RepositoryItem("cb617fd3-ec9d-48e8-943b-8125280be813")]
            public virtual Ranorex.SelectTag SelectCountry
            {
                get
                {
                    return _selectcountryInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SelectCountry item info.
            /// </summary>
            [RepositoryItemInfo("cb617fd3-ec9d-48e8-943b-8125280be813")]
            public virtual RepoItemInfo SelectCountryInfo
            {
                get
                {
                    return _selectcountryInfo;
                }
            }

            /// <summary>
            /// The TextAreaAddInfo item.
            /// </summary>
            [RepositoryItem("6f16e74b-de19-437e-9da0-de006703944e")]
            public virtual Ranorex.TextAreaTag TextAreaAddInfo
            {
                get
                {
                    return _textareaaddinfoInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The TextAreaAddInfo item info.
            /// </summary>
            [RepositoryItemInfo("6f16e74b-de19-437e-9da0-de006703944e")]
            public virtual RepoItemInfo TextAreaAddInfoInfo
            {
                get
                {
                    return _textareaaddinfoInfo;
                }
            }

            /// <summary>
            /// The InputMobilePhone item.
            /// </summary>
            [RepositoryItem("c9e1052f-45c6-4b40-a5ed-1dbb550f3b5b")]
            public virtual Ranorex.InputTag InputMobilePhone
            {
                get
                {
                    return _inputmobilephoneInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputMobilePhone item info.
            /// </summary>
            [RepositoryItemInfo("c9e1052f-45c6-4b40-a5ed-1dbb550f3b5b")]
            public virtual RepoItemInfo InputMobilePhoneInfo
            {
                get
                {
                    return _inputmobilephoneInfo;
                }
            }

            /// <summary>
            /// The InputAddressAlias item.
            /// </summary>
            [RepositoryItem("3b89129a-b7eb-48b0-b008-8f377540036b")]
            public virtual Ranorex.InputTag InputAddressAlias
            {
                get
                {
                    return _inputaddressaliasInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputAddressAlias item info.
            /// </summary>
            [RepositoryItemInfo("3b89129a-b7eb-48b0-b008-8f377540036b")]
            public virtual RepoItemInfo InputAddressAliasInfo
            {
                get
                {
                    return _inputaddressaliasInfo;
                }
            }

            /// <summary>
            /// The BtnRegister item.
            /// </summary>
            [RepositoryItem("a0cd9497-07ab-404c-b2d4-a4c5e1b11d76")]
            public virtual Ranorex.SpanTag BtnRegister
            {
                get
                {
                    return _btnregisterInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The BtnRegister item info.
            /// </summary>
            [RepositoryItemInfo("a0cd9497-07ab-404c-b2d4-a4c5e1b11d76")]
            public virtual RepoItemInfo BtnRegisterInfo
            {
                get
                {
                    return _btnregisterInfo;
                }
            }
        }

        /// <summary>
        /// The ContactUsPageFolder folder.
        /// </summary>
        [RepositoryFolder("a6b7c68b-5639-4431-a490-b345c5e3443b")]
        public partial class ContactUsPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _validatewelcometoyouraccounthereyoucanmaInfo;
            RepoItemInfo _contactusInfo;
            RepoItemInfo _idcontactInfo;
            RepoItemInfo _idorderInfo;
            RepoItemInfo _fileuploadInfo;
            RepoItemInfo _messageInfo;
            RepoItemInfo _sendInfo;
            RepoItemInfo _yourmessagehasbeensuccessfullysentInfo;
            RepoItemInfo _choosensubjectheadingInfo;
            RepoItemInfo _showoptionspanInfo;
            RepoItemInfo _emailInfo;

            /// <summary>
            /// Creates a new ContactUsPage  folder.
            /// </summary>
            public ContactUsPageFolder(RepoGenBaseFolder parentFolder) :
                    base("ContactUsPage", "", parentFolder, 0, null, false, "a6b7c68b-5639-4431-a490-b345c5e3443b", "")
            {
                _validatewelcometoyouraccounthereyoucanmaInfo = new RepoItemInfo(this, "ValidateWelcomeToYourAccountHereYouCanMa", ".//div[#'center_column']/p[@innertext>'Welcome to your account. Here']", ".//div[#'center_column']/p[@innertext>'Welcome to your account. Here']", 30000, null, "e780019e-64dd-49dc-82d7-9976ee2a1893");
                _contactusInfo = new RepoItemInfo(this, "ContactUs", ".//div[#'contact-link']/a[@innertext='Contact us']", ".//div[#'contact-link']/a[@innertext='Contact us']", 30000, null, "2d03f68f-d611-4a38-92ae-f2749cf24efd");
                _idcontactInfo = new RepoItemInfo(this, "IdContact", ".//div[#'uniform-id_contact']", ".//select[#'id_contact']", 30000, null, "b26aa5d8-46ee-4c21-821f-356d67041308");
                _idorderInfo = new RepoItemInfo(this, "IdOrder", ".//div[#'center_column']/form[@action='http://automationpractice.com/index.php?controller=contact']/fieldset/div[1]/div[1]/div[2]/?/?/select[@name='id_order']", ".//div[#'center_column']//select[@name='id_order']", 30000, null, "0ca5e426-bb3b-4bce-8032-9f33d13a1ecb");
                _fileuploadInfo = new RepoItemInfo(this, "FileUpload", ".//input[#'fileUpload']", ".//input[#'fileUpload']", 30000, null, "a055a1c9-d213-4bf2-9845-6a4023cd2fdb");
                _messageInfo = new RepoItemInfo(this, "Message", ".//textarea[#'message']", ".//textarea[#'message']", 30000, null, "771d8eea-2249-432c-bd59-cd57e536d4fb");
                _sendInfo = new RepoItemInfo(this, "Send", ".//button[#'submitMessage']/span[@innertext='Send']", ".//button[#'submitMessage']/span[@innertext='Send']", 30000, null, "f3beca06-edf6-436d-93d9-50ced2d16680");
                _yourmessagehasbeensuccessfullysentInfo = new RepoItemInfo(this, "YourMessageHasBeenSuccessfullySent", ".//div[#'center_column']/p[@innertext>'Your message has been successfully']", ".//div[#'center_column']/p[@innertext>'Your message has been successfully']", 30000, null, "7e44c17d-fdba-4988-a251-67877e99d209");
                _choosensubjectheadingInfo = new RepoItemInfo(this, "ChoosenSubjectHeading", ".//select[#'id_contact']/option[@innertext='Customer service']", "element", 30000, null, "cfb64bab-e1a9-4fc0-9917-992ec278e961");
                _showoptionspanInfo = new RepoItemInfo(this, "ShowOptionSpan", ".//div[#'uniform-id_contact']", "element", 30000, null, "dbf2509a-113c-4a35-b9dd-749afff33bc5");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", ".//input[#'email']", 30000, null, "4e55713a-7819-4275-bd08-b4d164bf211c");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a6b7c68b-5639-4431-a490-b345c5e3443b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ValidateWelcomeToYourAccountHereYouCanMa item.
            /// </summary>
            [RepositoryItem("e780019e-64dd-49dc-82d7-9976ee2a1893")]
            public virtual Ranorex.PTag ValidateWelcomeToYourAccountHereYouCanMa
            {
                get
                {
                    return _validatewelcometoyouraccounthereyoucanmaInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The ValidateWelcomeToYourAccountHereYouCanMa item info.
            /// </summary>
            [RepositoryItemInfo("e780019e-64dd-49dc-82d7-9976ee2a1893")]
            public virtual RepoItemInfo ValidateWelcomeToYourAccountHereYouCanMaInfo
            {
                get
                {
                    return _validatewelcometoyouraccounthereyoucanmaInfo;
                }
            }

            /// <summary>
            /// The ContactUs item.
            /// </summary>
            [RepositoryItem("2d03f68f-d611-4a38-92ae-f2749cf24efd")]
            public virtual Ranorex.ATag ContactUs
            {
                get
                {
                    return _contactusInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ContactUs item info.
            /// </summary>
            [RepositoryItemInfo("2d03f68f-d611-4a38-92ae-f2749cf24efd")]
            public virtual RepoItemInfo ContactUsInfo
            {
                get
                {
                    return _contactusInfo;
                }
            }

            /// <summary>
            /// The IdContact item.
            /// </summary>
            [RepositoryItem("b26aa5d8-46ee-4c21-821f-356d67041308")]
            public virtual Ranorex.DivTag IdContact
            {
                get
                {
                    return _idcontactInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The IdContact item info.
            /// </summary>
            [RepositoryItemInfo("b26aa5d8-46ee-4c21-821f-356d67041308")]
            public virtual RepoItemInfo IdContactInfo
            {
                get
                {
                    return _idcontactInfo;
                }
            }

            /// <summary>
            /// The IdOrder item.
            /// </summary>
            [RepositoryItem("0ca5e426-bb3b-4bce-8032-9f33d13a1ecb")]
            public virtual Ranorex.SelectTag IdOrder
            {
                get
                {
                    return _idorderInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The IdOrder item info.
            /// </summary>
            [RepositoryItemInfo("0ca5e426-bb3b-4bce-8032-9f33d13a1ecb")]
            public virtual RepoItemInfo IdOrderInfo
            {
                get
                {
                    return _idorderInfo;
                }
            }

            /// <summary>
            /// The FileUpload item.
            /// </summary>
            [RepositoryItem("a055a1c9-d213-4bf2-9845-6a4023cd2fdb")]
            public virtual Ranorex.InputTag FileUpload
            {
                get
                {
                    return _fileuploadInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FileUpload item info.
            /// </summary>
            [RepositoryItemInfo("a055a1c9-d213-4bf2-9845-6a4023cd2fdb")]
            public virtual RepoItemInfo FileUploadInfo
            {
                get
                {
                    return _fileuploadInfo;
                }
            }

            /// <summary>
            /// The Message item.
            /// </summary>
            [RepositoryItem("771d8eea-2249-432c-bd59-cd57e536d4fb")]
            public virtual Ranorex.TextAreaTag Message
            {
                get
                {
                    return _messageInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The Message item info.
            /// </summary>
            [RepositoryItemInfo("771d8eea-2249-432c-bd59-cd57e536d4fb")]
            public virtual RepoItemInfo MessageInfo
            {
                get
                {
                    return _messageInfo;
                }
            }

            /// <summary>
            /// The Send item.
            /// </summary>
            [RepositoryItem("f3beca06-edf6-436d-93d9-50ced2d16680")]
            public virtual Ranorex.SpanTag Send
            {
                get
                {
                    return _sendInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Send item info.
            /// </summary>
            [RepositoryItemInfo("f3beca06-edf6-436d-93d9-50ced2d16680")]
            public virtual RepoItemInfo SendInfo
            {
                get
                {
                    return _sendInfo;
                }
            }

            /// <summary>
            /// The YourMessageHasBeenSuccessfullySent item.
            /// </summary>
            [RepositoryItem("7e44c17d-fdba-4988-a251-67877e99d209")]
            public virtual Ranorex.PTag YourMessageHasBeenSuccessfullySent
            {
                get
                {
                    return _yourmessagehasbeensuccessfullysentInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The YourMessageHasBeenSuccessfullySent item info.
            /// </summary>
            [RepositoryItemInfo("7e44c17d-fdba-4988-a251-67877e99d209")]
            public virtual RepoItemInfo YourMessageHasBeenSuccessfullySentInfo
            {
                get
                {
                    return _yourmessagehasbeensuccessfullysentInfo;
                }
            }

            /// <summary>
            /// The ChoosenSubjectHeading item.
            /// </summary>
            [RepositoryItem("cfb64bab-e1a9-4fc0-9917-992ec278e961")]
            public virtual Ranorex.OptionTag ChoosenSubjectHeading
            {
                get
                {
                    return _choosensubjectheadingInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The ChoosenSubjectHeading item info.
            /// </summary>
            [RepositoryItemInfo("cfb64bab-e1a9-4fc0-9917-992ec278e961")]
            public virtual RepoItemInfo ChoosenSubjectHeadingInfo
            {
                get
                {
                    return _choosensubjectheadingInfo;
                }
            }

            /// <summary>
            /// The ShowOptionSpan item.
            /// </summary>
            [RepositoryItem("dbf2509a-113c-4a35-b9dd-749afff33bc5")]
            public virtual Ranorex.DivTag ShowOptionSpan
            {
                get
                {
                    return _showoptionspanInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ShowOptionSpan item info.
            /// </summary>
            [RepositoryItemInfo("dbf2509a-113c-4a35-b9dd-749afff33bc5")]
            public virtual RepoItemInfo ShowOptionSpanInfo
            {
                get
                {
                    return _showoptionspanInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("4e55713a-7819-4275-bd08-b4d164bf211c")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("4e55713a-7819-4275-bd08-b4d164bf211c")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }
        }

        /// <summary>
        /// The ShoppingCardSumaryFolder folder.
        /// </summary>
        [RepositoryFolder("6724994c-4adf-4412-b258-7307e31d4079")]
        public partial class ShoppingCardSumaryFolder : RepoGenBaseFolder
        {
            TestWebRepositoryFolders.HomefeaturedFolder _homefeatured;
            TestWebRepositoryFolders.CenterColumnFolder _centercolumn;
            TestWebRepositoryFolders.ItemSelectFolder _itemselect;
            TestWebRepositoryFolders.QuantityItemFolder _quantityitem;
            TestWebRepositoryFolders.ItemSaleSelectFolder _itemsaleselect;
            RepoItemInfo _continueshoppingInfo;
            RepoItemInfo _spantagcheckoutInfo;
            RepoItemInfo _textareaaddcommentInfo;
            RepoItemInfo _inputtagcgvInfo;
            RepoItemInfo _spantagproceedtocheckoutInfo;
            RepoItemInfo _iconfirmmyorderInfo;

            /// <summary>
            /// Creates a new ShoppingCardSumary  folder.
            /// </summary>
            public ShoppingCardSumaryFolder(RepoGenBaseFolder parentFolder) :
                    base("ShoppingCardSumary", "", parentFolder, 0, null, false, "6724994c-4adf-4412-b258-7307e31d4079", "")
            {
                _homefeatured = new TestWebRepositoryFolders.HomefeaturedFolder(this);
                _centercolumn = new TestWebRepositoryFolders.CenterColumnFolder(this);
                _itemselect = new TestWebRepositoryFolders.ItemSelectFolder(this);
                _quantityitem = new TestWebRepositoryFolders.QuantityItemFolder(this);
                _itemsaleselect = new TestWebRepositoryFolders.ItemSaleSelectFolder(this);
                _continueshoppingInfo = new RepoItemInfo(this, "ContinueShopping", ".//div[@id='layer_cart' and @style~'display: block']//span[@title='Continue shopping' and @visible='true']", ".//div[#'layer_cart']//span[@innertext='Continue shopping']", 30000, null, "fa438543-5a09-4709-b562-b8d02b8c9e55");
                _spantagcheckoutInfo = new RepoItemInfo(this, "SpanTagCheckOut", ".//div[@class='cart_block block exclusive' and @style~'display: block']//a[@id='button_order_cart']", ".//a[#'button_order_cart']/span[@innertext='Check out']", 30000, null, "6e9ac1ea-4b01-41e3-b14a-80945a159459");
                _textareaaddcommentInfo = new RepoItemInfo(this, "TextAreaAddComment", ".//div[#'ordermsg']/textarea[@required='False']", ".//div[#'ordermsg']/textarea[@required='False']", 30000, null, "fe18b7e5-cd06-4840-95bc-6a23074efc29");
                _inputtagcgvInfo = new RepoItemInfo(this, "InputTagCgv", ".//div[#'uniform-cgv']", ".//input[#'cgv']", 30000, null, "9287a437-24f8-4a29-8361-67e994a2bc85");
                _spantagproceedtocheckoutInfo = new RepoItemInfo(this, "SpanTagProceedToCheckout", ".//form[#'form']//span[@innertext>'Proceed to checkout']", ".//form[#'form']//span[@innertext>'Proceed to checkout']", 30000, null, "d246ed89-c6cd-4cd3-bd16-c601469b33a4");
                _iconfirmmyorderInfo = new RepoItemInfo(this, "IConfirmMyOrder", ".//p[#'cart_navigation']/?/?/span[@innertext='I confirm my order']", ".//p[#'cart_navigation']/?/?/span[@innertext='I confirm my order']", 30000, null, "2c4f5258-8421-463d-a11c-10d7bb1e0e21");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6724994c-4adf-4412-b258-7307e31d4079")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContinueShopping item.
            /// </summary>
            [RepositoryItem("fa438543-5a09-4709-b562-b8d02b8c9e55")]
            public virtual Ranorex.SpanTag ContinueShopping
            {
                get
                {
                    return _continueshoppingInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ContinueShopping item info.
            /// </summary>
            [RepositoryItemInfo("fa438543-5a09-4709-b562-b8d02b8c9e55")]
            public virtual RepoItemInfo ContinueShoppingInfo
            {
                get
                {
                    return _continueshoppingInfo;
                }
            }

            /// <summary>
            /// The SpanTagCheckOut item.
            /// </summary>
            [RepositoryItem("6e9ac1ea-4b01-41e3-b14a-80945a159459")]
            public virtual Ranorex.ATag SpanTagCheckOut
            {
                get
                {
                    return _spantagcheckoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SpanTagCheckOut item info.
            /// </summary>
            [RepositoryItemInfo("6e9ac1ea-4b01-41e3-b14a-80945a159459")]
            public virtual RepoItemInfo SpanTagCheckOutInfo
            {
                get
                {
                    return _spantagcheckoutInfo;
                }
            }

            /// <summary>
            /// The TextAreaAddComment item.
            /// </summary>
            [RepositoryItem("fe18b7e5-cd06-4840-95bc-6a23074efc29")]
            public virtual Ranorex.TextAreaTag TextAreaAddComment
            {
                get
                {
                    return _textareaaddcommentInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The TextAreaAddComment item info.
            /// </summary>
            [RepositoryItemInfo("fe18b7e5-cd06-4840-95bc-6a23074efc29")]
            public virtual RepoItemInfo TextAreaAddCommentInfo
            {
                get
                {
                    return _textareaaddcommentInfo;
                }
            }

            /// <summary>
            /// The InputTagCgv item.
            /// </summary>
            [RepositoryItem("9287a437-24f8-4a29-8361-67e994a2bc85")]
            public virtual Ranorex.DivTag InputTagCgv
            {
                get
                {
                    return _inputtagcgvInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The InputTagCgv item info.
            /// </summary>
            [RepositoryItemInfo("9287a437-24f8-4a29-8361-67e994a2bc85")]
            public virtual RepoItemInfo InputTagCgvInfo
            {
                get
                {
                    return _inputtagcgvInfo;
                }
            }

            /// <summary>
            /// The SpanTagProceedToCheckout item.
            /// </summary>
            [RepositoryItem("d246ed89-c6cd-4cd3-bd16-c601469b33a4")]
            public virtual Ranorex.SpanTag SpanTagProceedToCheckout
            {
                get
                {
                    return _spantagproceedtocheckoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagProceedToCheckout item info.
            /// </summary>
            [RepositoryItemInfo("d246ed89-c6cd-4cd3-bd16-c601469b33a4")]
            public virtual RepoItemInfo SpanTagProceedToCheckoutInfo
            {
                get
                {
                    return _spantagproceedtocheckoutInfo;
                }
            }

            /// <summary>
            /// The IConfirmMyOrder item.
            /// </summary>
            [RepositoryItem("2c4f5258-8421-463d-a11c-10d7bb1e0e21")]
            public virtual Ranorex.SpanTag IConfirmMyOrder
            {
                get
                {
                    return _iconfirmmyorderInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The IConfirmMyOrder item info.
            /// </summary>
            [RepositoryItemInfo("2c4f5258-8421-463d-a11c-10d7bb1e0e21")]
            public virtual RepoItemInfo IConfirmMyOrderInfo
            {
                get
                {
                    return _iconfirmmyorderInfo;
                }
            }

            /// <summary>
            /// The Homefeatured folder.
            /// </summary>
            [RepositoryFolder("097c84fa-075f-4904-b848-ed6c4b012a81")]
            public virtual TestWebRepositoryFolders.HomefeaturedFolder Homefeatured
            {
                get { return _homefeatured; }
            }

            /// <summary>
            /// The CenterColumn folder.
            /// </summary>
            [RepositoryFolder("e4934917-c81c-4183-a306-c621d5dc6738")]
            public virtual TestWebRepositoryFolders.CenterColumnFolder CenterColumn
            {
                get { return _centercolumn; }
            }

            /// <summary>
            /// The ItemSelect folder.
            /// </summary>
            [RepositoryFolder("78ebbd1a-ea63-4c26-ba72-17c3f7597fa7")]
            public virtual TestWebRepositoryFolders.ItemSelectFolder ItemSelect
            {
                get { return _itemselect; }
            }

            /// <summary>
            /// The QuantityItem folder.
            /// </summary>
            [RepositoryFolder("fab605a5-305e-4a80-88e1-6300f71727bd")]
            public virtual TestWebRepositoryFolders.QuantityItemFolder QuantityItem
            {
                get { return _quantityitem; }
            }

            /// <summary>
            /// The ItemSaleSelect folder.
            /// </summary>
            [RepositoryFolder("7a8dc3ed-7a87-45b1-bed3-5ce500e840e2")]
            public virtual TestWebRepositoryFolders.ItemSaleSelectFolder ItemSaleSelect
            {
                get { return _itemsaleselect; }
            }
        }

        /// <summary>
        /// The HomefeaturedFolder folder.
        /// </summary>
        [RepositoryFolder("097c84fa-075f-4904-b848-ed6c4b012a81")]
        public partial class HomefeaturedFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addtocartInfo;
            RepoItemInfo _addtocart1Info;
            RepoItemInfo _addtocart2Info;

            /// <summary>
            /// Creates a new Homefeatured  folder.
            /// </summary>
            public HomefeaturedFolder(RepoGenBaseFolder parentFolder) :
                    base("Homefeatured", ".//ul[#'homefeatured']", parentFolder, 30000, null, false, "097c84fa-075f-4904-b848-ed6c4b012a81", "")
            {
                _addtocartInfo = new RepoItemInfo(this, "AddToCart", "li[1]//a[@title='Add to cart']/span[@innertext='Add to cart']", ".//span[@innertext='Add to cart']", 30000, null, "8bb99e4b-0c79-4411-a1f6-88c5d26139f0");
                _addtocart1Info = new RepoItemInfo(this, "AddToCart1", "li[2]//a[@title='Add to cart']/span[@innertext='Add to cart']", "li[2]/div/div[2]/div[2]/a[@title='Add to cart']/span[@innertext='Add to cart']", 30000, null, "e9a89798-2995-4fc7-9bf1-65ce639180ed");
                _addtocart2Info = new RepoItemInfo(this, "AddToCart2", "li[3]//a[@title='Add to cart']/span[@innertext='Add to cart']", "li[3]/div/div[2]/div[2]/a[@title='Add to cart']/span[@innertext='Add to cart']", 30000, null, "80e8d99b-5f8b-490b-98bb-048fc801744c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("097c84fa-075f-4904-b848-ed6c4b012a81")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("097c84fa-075f-4904-b848-ed6c4b012a81")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddToCart item.
            /// </summary>
            [RepositoryItem("8bb99e4b-0c79-4411-a1f6-88c5d26139f0")]
            public virtual Ranorex.SpanTag AddToCart
            {
                get
                {
                    return _addtocartInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AddToCart item info.
            /// </summary>
            [RepositoryItemInfo("8bb99e4b-0c79-4411-a1f6-88c5d26139f0")]
            public virtual RepoItemInfo AddToCartInfo
            {
                get
                {
                    return _addtocartInfo;
                }
            }

            /// <summary>
            /// The AddToCart1 item.
            /// </summary>
            [RepositoryItem("e9a89798-2995-4fc7-9bf1-65ce639180ed")]
            public virtual Ranorex.SpanTag AddToCart1
            {
                get
                {
                    return _addtocart1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AddToCart1 item info.
            /// </summary>
            [RepositoryItemInfo("e9a89798-2995-4fc7-9bf1-65ce639180ed")]
            public virtual RepoItemInfo AddToCart1Info
            {
                get
                {
                    return _addtocart1Info;
                }
            }

            /// <summary>
            /// The AddToCart2 item.
            /// </summary>
            [RepositoryItem("80e8d99b-5f8b-490b-98bb-048fc801744c")]
            public virtual Ranorex.SpanTag AddToCart2
            {
                get
                {
                    return _addtocart2Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AddToCart2 item info.
            /// </summary>
            [RepositoryItemInfo("80e8d99b-5f8b-490b-98bb-048fc801744c")]
            public virtual RepoItemInfo AddToCart2Info
            {
                get
                {
                    return _addtocart2Info;
                }
            }
        }

        /// <summary>
        /// The CenterColumnFolder folder.
        /// </summary>
        [RepositoryFolder("e4934917-c81c-4183-a306-c621d5dc6738")]
        public partial class CenterColumnFolder : RepoGenBaseFolder
        {
            RepoItemInfo _proceedtocheckoutInfo;
            RepoItemInfo _paybycheckInfo;
            RepoItemInfo _proceedtocheckout1Info;
            RepoItemInfo _yourorderonmystoreiscompleteInfo;
            RepoItemInfo _formgroupselector1Info;

            /// <summary>
            /// Creates a new CenterColumn  folder.
            /// </summary>
            public CenterColumnFolder(RepoGenBaseFolder parentFolder) :
                    base("CenterColumn", ".//div[#'center_column']", parentFolder, 30000, null, false, "e4934917-c81c-4183-a306-c621d5dc6738", "")
            {
                _proceedtocheckoutInfo = new RepoItemInfo(this, "ProceedToCheckout", ".//span[@innertext='Proceed to checkout'][1]", ".//span[@innertext='Proceed to checkout']", 30000, null, "76d4847e-863b-4f3b-a504-52dccd1fc60d");
                _paybycheckInfo = new RepoItemInfo(this, "PayByCheck", "div/div[3]//a[@innertext>'                Pay by check']", ".//a[@innertext>'                Pay by check']", 30000, null, "d9e85a46-652a-44d3-a3a4-e97a0a3dfa9d");
                _proceedtocheckout1Info = new RepoItemInfo(this, "ProceedToCheckout1", "form[@action='http://automationpractice.com/index.php?controller=order']//span[@innertext='Proceed to checkout']", ".//span[@innertext='Proceed to checkout']", 30000, null, "b72cc9e3-15fa-405a-9321-56aa643d4542");
                _yourorderonmystoreiscompleteInfo = new RepoItemInfo(this, "YourOrderOnMyStoreIsComplete", "p[@innertext>'Your order on My Store is']", "p[@innertext>'Your order on My Store is']", 30000, null, "35191456-e5a9-47ce-ac95-a093534ef6c0");
                _formgroupselector1Info = new RepoItemInfo(this, "FormGroupSelector1", "form[@action='http://automationpractice.com/index.php?controller=contact']/fieldset/div[1]/div[1]/div[1]", "?/?/fieldset/div[1]/div[1]/div[1]", 30000, null, "2af19ea9-d3b6-463e-821c-19e82f161140");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e4934917-c81c-4183-a306-c621d5dc6738")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e4934917-c81c-4183-a306-c621d5dc6738")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProceedToCheckout item.
            /// </summary>
            [RepositoryItem("76d4847e-863b-4f3b-a504-52dccd1fc60d")]
            public virtual Ranorex.SpanTag ProceedToCheckout
            {
                get
                {
                    return _proceedtocheckoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ProceedToCheckout item info.
            /// </summary>
            [RepositoryItemInfo("76d4847e-863b-4f3b-a504-52dccd1fc60d")]
            public virtual RepoItemInfo ProceedToCheckoutInfo
            {
                get
                {
                    return _proceedtocheckoutInfo;
                }
            }

            /// <summary>
            /// The PayByCheck item.
            /// </summary>
            [RepositoryItem("d9e85a46-652a-44d3-a3a4-e97a0a3dfa9d")]
            public virtual Ranorex.ATag PayByCheck
            {
                get
                {
                    return _paybycheckInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The PayByCheck item info.
            /// </summary>
            [RepositoryItemInfo("d9e85a46-652a-44d3-a3a4-e97a0a3dfa9d")]
            public virtual RepoItemInfo PayByCheckInfo
            {
                get
                {
                    return _paybycheckInfo;
                }
            }

            /// <summary>
            /// The ProceedToCheckout1 item.
            /// </summary>
            [RepositoryItem("b72cc9e3-15fa-405a-9321-56aa643d4542")]
            public virtual Ranorex.SpanTag ProceedToCheckout1
            {
                get
                {
                    return _proceedtocheckout1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ProceedToCheckout1 item info.
            /// </summary>
            [RepositoryItemInfo("b72cc9e3-15fa-405a-9321-56aa643d4542")]
            public virtual RepoItemInfo ProceedToCheckout1Info
            {
                get
                {
                    return _proceedtocheckout1Info;
                }
            }

            /// <summary>
            /// The YourOrderOnMyStoreIsComplete item.
            /// </summary>
            [RepositoryItem("35191456-e5a9-47ce-ac95-a093534ef6c0")]
            public virtual Ranorex.PTag YourOrderOnMyStoreIsComplete
            {
                get
                {
                    return _yourorderonmystoreiscompleteInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The YourOrderOnMyStoreIsComplete item info.
            /// </summary>
            [RepositoryItemInfo("35191456-e5a9-47ce-ac95-a093534ef6c0")]
            public virtual RepoItemInfo YourOrderOnMyStoreIsCompleteInfo
            {
                get
                {
                    return _yourorderonmystoreiscompleteInfo;
                }
            }

            /// <summary>
            /// The FormGroupSelector1 item.
            /// </summary>
            [RepositoryItem("2af19ea9-d3b6-463e-821c-19e82f161140")]
            public virtual Ranorex.DivTag FormGroupSelector1
            {
                get
                {
                    return _formgroupselector1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FormGroupSelector1 item info.
            /// </summary>
            [RepositoryItemInfo("2af19ea9-d3b6-463e-821c-19e82f161140")]
            public virtual RepoItemInfo FormGroupSelector1Info
            {
                get
                {
                    return _formgroupselector1Info;
                }
            }
        }

        /// <summary>
        /// The ItemSelectFolder folder.
        /// </summary>
        [RepositoryFolder("78ebbd1a-ea63-4c26-ba72-17c3f7597fa7")]
        public partial class ItemSelectFolder : RepoGenBaseFolder
        {
            RepoItemInfo _item1Info;
            RepoItemInfo _item2Info;
            RepoItemInfo _item3Info;
            RepoItemInfo _hovercartInfo;
            RepoItemInfo _nameproductInfo;

            /// <summary>
            /// Creates a new ItemSelect  folder.
            /// </summary>
            public ItemSelectFolder(RepoGenBaseFolder parentFolder) :
                    base("ItemSelect", "", parentFolder, 0, null, false, "78ebbd1a-ea63-4c26-ba72-17c3f7597fa7", "")
            {
                _item1Info = new RepoItemInfo(this, "Item1", ".//div[@class='product-container'][1]", "element", 30000, null, "7ac153c5-df3e-4f45-9176-78e44954b1e1");
                _item2Info = new RepoItemInfo(this, "Item2", ".//div[@class='product-container'][2]", "element", 30000, null, "3fad418c-4932-4842-955d-e4208b887308");
                _item3Info = new RepoItemInfo(this, "Item3", ".//div[@class='product-container'][3]", "element", 30000, null, "6180683f-a423-4408-8a12-2d0102e979d9");
                _hovercartInfo = new RepoItemInfo(this, "HoverCart", ".///a[@title='View my shopping cart']", "element", 30000, null, "9e804264-181c-4965-955f-487bb5b8cfa4");
                _nameproductInfo = new RepoItemInfo(this, "NameProduct", ".//ul[#'homefeatured']//div[@class='right-block']//a[@title~'Printed']", "element", 30000, null, "1291892f-099c-4094-a1be-b39a3a900258");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("78ebbd1a-ea63-4c26-ba72-17c3f7597fa7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Item1 item.
            /// </summary>
            [RepositoryItem("7ac153c5-df3e-4f45-9176-78e44954b1e1")]
            public virtual Ranorex.DivTag Item1
            {
                get
                {
                    return _item1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Item1 item info.
            /// </summary>
            [RepositoryItemInfo("7ac153c5-df3e-4f45-9176-78e44954b1e1")]
            public virtual RepoItemInfo Item1Info
            {
                get
                {
                    return _item1Info;
                }
            }

            /// <summary>
            /// The Item2 item.
            /// </summary>
            [RepositoryItem("3fad418c-4932-4842-955d-e4208b887308")]
            public virtual Ranorex.DivTag Item2
            {
                get
                {
                    return _item2Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Item2 item info.
            /// </summary>
            [RepositoryItemInfo("3fad418c-4932-4842-955d-e4208b887308")]
            public virtual RepoItemInfo Item2Info
            {
                get
                {
                    return _item2Info;
                }
            }

            /// <summary>
            /// The Item3 item.
            /// </summary>
            [RepositoryItem("6180683f-a423-4408-8a12-2d0102e979d9")]
            public virtual Ranorex.DivTag Item3
            {
                get
                {
                    return _item3Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Item3 item info.
            /// </summary>
            [RepositoryItemInfo("6180683f-a423-4408-8a12-2d0102e979d9")]
            public virtual RepoItemInfo Item3Info
            {
                get
                {
                    return _item3Info;
                }
            }

            /// <summary>
            /// The HoverCart item.
            /// </summary>
            [RepositoryItem("9e804264-181c-4965-955f-487bb5b8cfa4")]
            public virtual Ranorex.ATag HoverCart
            {
                get
                {
                    return _hovercartInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HoverCart item info.
            /// </summary>
            [RepositoryItemInfo("9e804264-181c-4965-955f-487bb5b8cfa4")]
            public virtual RepoItemInfo HoverCartInfo
            {
                get
                {
                    return _hovercartInfo;
                }
            }

            /// <summary>
            /// The NameProduct item.
            /// </summary>
            [RepositoryItem("1291892f-099c-4094-a1be-b39a3a900258")]
            public virtual Ranorex.ATag NameProduct
            {
                get
                {
                    return _nameproductInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NameProduct item info.
            /// </summary>
            [RepositoryItemInfo("1291892f-099c-4094-a1be-b39a3a900258")]
            public virtual RepoItemInfo NameProductInfo
            {
                get
                {
                    return _nameproductInfo;
                }
            }
        }

        /// <summary>
        /// The QuantityItemFolder folder.
        /// </summary>
        [RepositoryFolder("fab605a5-305e-4a80-88e1-6300f71727bd")]
        public partial class QuantityItemFolder : RepoGenBaseFolder
        {
            RepoItemInfo _quantityitemrepoInfo;
            RepoItemInfo _totalquantityitemInfo;
            RepoItemInfo _itempriceInfo;
            RepoItemInfo _totalproductsInfo;
            RepoItemInfo _totalshippingInfo;
            RepoItemInfo _totalpricewithouttaxInfo;
            RepoItemInfo _taxpriceInfo;
            RepoItemInfo _totalpriceInfo;

            /// <summary>
            /// Creates a new QuantityItem  folder.
            /// </summary>
            public QuantityItemFolder(RepoGenBaseFolder parentFolder) :
                    base("QuantityItem", "", parentFolder, 0, null, false, "fab605a5-305e-4a80-88e1-6300f71727bd", "")
            {
                _quantityitemrepoInfo = new RepoItemInfo(this, "QuantityItemRepo", ".//span[@class='quantity']", "element", 30000, null, "886f4c58-ffbe-4f36-a13d-b58d8a42b768");
                _totalquantityitemInfo = new RepoItemInfo(this, "TotalQuantityItem", ".//span[@class='ajax_cart_quantity'][1]", "element", 30000, null, "de750567-8c77-4d06-bc7f-76d5c25c0d84");
                _itempriceInfo = new RepoItemInfo(this, "ItemPrice", ".//td[@data-title='Total']/span[@class='price']", "element", 30000, null, "cfb3089a-fef7-417f-8101-ab9b8e29056d");
                _totalproductsInfo = new RepoItemInfo(this, "TotalProducts", ".//td[#'total_product']", "element", 30000, null, "771c78c1-d052-41f1-86ff-68db3259197a");
                _totalshippingInfo = new RepoItemInfo(this, "TotalShipping", ".//td[#'total_shipping']", "element", 30000, null, "f8195ea9-b797-4a87-931c-53cbbf041441");
                _totalpricewithouttaxInfo = new RepoItemInfo(this, "TotalPriceWithoutTax", ".//td[#'total_price_without_tax']", "element", 30000, null, "77771233-8dec-4a36-9f48-87f660a7a111");
                _taxpriceInfo = new RepoItemInfo(this, "TaxPrice", ".//td[#'total_tax']", "element", 30000, null, "7eb1ebe3-5491-4c5e-968e-be3cdfd2c130");
                _totalpriceInfo = new RepoItemInfo(this, "TotalPrice", ".//span[#'total_price']", "element", 30000, null, "d88269e5-62ed-4cff-8729-c1ee2542277f");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fab605a5-305e-4a80-88e1-6300f71727bd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The QuantityItemRepo item.
            /// </summary>
            [RepositoryItem("886f4c58-ffbe-4f36-a13d-b58d8a42b768")]
            public virtual Ranorex.SpanTag QuantityItemRepo
            {
                get
                {
                    return _quantityitemrepoInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The QuantityItemRepo item info.
            /// </summary>
            [RepositoryItemInfo("886f4c58-ffbe-4f36-a13d-b58d8a42b768")]
            public virtual RepoItemInfo QuantityItemRepoInfo
            {
                get
                {
                    return _quantityitemrepoInfo;
                }
            }

            /// <summary>
            /// The TotalQuantityItem item.
            /// </summary>
            [RepositoryItem("de750567-8c77-4d06-bc7f-76d5c25c0d84")]
            public virtual Ranorex.SpanTag TotalQuantityItem
            {
                get
                {
                    return _totalquantityitemInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TotalQuantityItem item info.
            /// </summary>
            [RepositoryItemInfo("de750567-8c77-4d06-bc7f-76d5c25c0d84")]
            public virtual RepoItemInfo TotalQuantityItemInfo
            {
                get
                {
                    return _totalquantityitemInfo;
                }
            }

            /// <summary>
            /// The ItemPrice item.
            /// </summary>
            [RepositoryItem("cfb3089a-fef7-417f-8101-ab9b8e29056d")]
            public virtual Ranorex.SpanTag ItemPrice
            {
                get
                {
                    return _itempriceInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ItemPrice item info.
            /// </summary>
            [RepositoryItemInfo("cfb3089a-fef7-417f-8101-ab9b8e29056d")]
            public virtual RepoItemInfo ItemPriceInfo
            {
                get
                {
                    return _itempriceInfo;
                }
            }

            /// <summary>
            /// The TotalProducts item.
            /// </summary>
            [RepositoryItem("771c78c1-d052-41f1-86ff-68db3259197a")]
            public virtual Ranorex.TdTag TotalProducts
            {
                get
                {
                    return _totalproductsInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The TotalProducts item info.
            /// </summary>
            [RepositoryItemInfo("771c78c1-d052-41f1-86ff-68db3259197a")]
            public virtual RepoItemInfo TotalProductsInfo
            {
                get
                {
                    return _totalproductsInfo;
                }
            }

            /// <summary>
            /// The TotalShipping item.
            /// </summary>
            [RepositoryItem("f8195ea9-b797-4a87-931c-53cbbf041441")]
            public virtual Ranorex.TdTag TotalShipping
            {
                get
                {
                    return _totalshippingInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The TotalShipping item info.
            /// </summary>
            [RepositoryItemInfo("f8195ea9-b797-4a87-931c-53cbbf041441")]
            public virtual RepoItemInfo TotalShippingInfo
            {
                get
                {
                    return _totalshippingInfo;
                }
            }

            /// <summary>
            /// The TotalPriceWithoutTax item.
            /// </summary>
            [RepositoryItem("77771233-8dec-4a36-9f48-87f660a7a111")]
            public virtual Ranorex.TdTag TotalPriceWithoutTax
            {
                get
                {
                    return _totalpricewithouttaxInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The TotalPriceWithoutTax item info.
            /// </summary>
            [RepositoryItemInfo("77771233-8dec-4a36-9f48-87f660a7a111")]
            public virtual RepoItemInfo TotalPriceWithoutTaxInfo
            {
                get
                {
                    return _totalpricewithouttaxInfo;
                }
            }

            /// <summary>
            /// The TaxPrice item.
            /// </summary>
            [RepositoryItem("7eb1ebe3-5491-4c5e-968e-be3cdfd2c130")]
            public virtual Ranorex.TdTag TaxPrice
            {
                get
                {
                    return _taxpriceInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The TaxPrice item info.
            /// </summary>
            [RepositoryItemInfo("7eb1ebe3-5491-4c5e-968e-be3cdfd2c130")]
            public virtual RepoItemInfo TaxPriceInfo
            {
                get
                {
                    return _taxpriceInfo;
                }
            }

            /// <summary>
            /// The TotalPrice item.
            /// </summary>
            [RepositoryItem("d88269e5-62ed-4cff-8729-c1ee2542277f")]
            public virtual Ranorex.SpanTag TotalPrice
            {
                get
                {
                    return _totalpriceInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TotalPrice item info.
            /// </summary>
            [RepositoryItemInfo("d88269e5-62ed-4cff-8729-c1ee2542277f")]
            public virtual RepoItemInfo TotalPriceInfo
            {
                get
                {
                    return _totalpriceInfo;
                }
            }
        }

        /// <summary>
        /// The ItemSaleSelectFolder folder.
        /// </summary>
        [RepositoryFolder("7a8dc3ed-7a87-45b1-bed3-5ce500e840e2")]
        public partial class ItemSaleSelectFolder : RepoGenBaseFolder
        {
            RepoItemInfo _itemsaleInfo;
            RepoItemInfo _addtocartInfo;

            /// <summary>
            /// Creates a new ItemSaleSelect  folder.
            /// </summary>
            public ItemSaleSelectFolder(RepoGenBaseFolder parentFolder) :
                    base("ItemSaleSelect", "", parentFolder, 0, null, false, "7a8dc3ed-7a87-45b1-bed3-5ce500e840e2", "")
            {
                _itemsaleInfo = new RepoItemInfo(this, "ItemSale", ".//ul[@id='homefeatured']//div[@class='right-block']//span[@class='price-percent-reduction']/../../..", "element", 30000, null, "f43ea886-5d51-4d30-858b-88a0539057f5");
                _addtocartInfo = new RepoItemInfo(this, "AddToCart", ".//ul[@id='homefeatured']/li[@class~'hovered']//div[@class='right-block']//div[@class='button-container']/a[1]", "element", 30000, null, "11750fa5-e84f-4672-b114-c65c3cd2e27f");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7a8dc3ed-7a87-45b1-bed3-5ce500e840e2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ItemSale item.
            /// </summary>
            [RepositoryItem("f43ea886-5d51-4d30-858b-88a0539057f5")]
            public virtual Ranorex.Unknown ItemSale
            {
                get
                {
                    return _itemsaleInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ItemSale item info.
            /// </summary>
            [RepositoryItemInfo("f43ea886-5d51-4d30-858b-88a0539057f5")]
            public virtual RepoItemInfo ItemSaleInfo
            {
                get
                {
                    return _itemsaleInfo;
                }
            }

            /// <summary>
            /// The AddToCart item.
            /// </summary>
            [RepositoryItem("11750fa5-e84f-4672-b114-c65c3cd2e27f")]
            public virtual Ranorex.ATag AddToCart
            {
                get
                {
                    return _addtocartInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AddToCart item info.
            /// </summary>
            [RepositoryItemInfo("11750fa5-e84f-4672-b114-c65c3cd2e27f")]
            public virtual RepoItemInfo AddToCartInfo
            {
                get
                {
                    return _addtocartInfo;
                }
            }
        }

        /// <summary>
        /// The LoginMyStoreGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("5dedd440-8a4d-4db6-ae63-bf12bcda4d37")]
        public partial class LoginMyStoreGoogleChromeAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new LoginMyStoreGoogleChrome  folder.
            /// </summary>
            public LoginMyStoreGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginMyStoreGoogleChrome", "/form[@title>'Login - My Store - Google']", parentFolder, 30000, null, true, "5dedd440-8a4d-4db6-ae63-bf12bcda4d37", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5dedd440-8a4d-4db6-ae63-bf12bcda4d37")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5dedd440-8a4d-4db6-ae63-bf12bcda4d37")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The OpenAppFolder folder.
        /// </summary>
        [RepositoryFolder("d6037ea3-3243-45a3-b837-8375fedc91e1")]
        public partial class OpenAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _baselineimageInfo;
            RepoItemInfo _buttonopenInfo;

            /// <summary>
            /// Creates a new Open  folder.
            /// </summary>
            public OpenAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Open", "/form[@title='Open']", parentFolder, 30000, null, true, "d6037ea3-3243-45a3-b837-8375fedc91e1", "")
            {
                _baselineimageInfo = new RepoItemInfo(this, "BaselineImage", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/?/?/listitem[@automationid='9']/picture[@automationid='BaselineImage']", ".//listitem[@automationid='9']/picture[@automationid='BaselineImage']", 30000, null, "af8e4a4f-9239-4240-97df-aedb230a6e7f");
                _buttonopenInfo = new RepoItemInfo(this, "ButtonOpen", "button[@text='&Open']", "button[@text='&Open']", 30000, null, "733e6283-6084-46e4-9cf0-224195313091");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d6037ea3-3243-45a3-b837-8375fedc91e1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d6037ea3-3243-45a3-b837-8375fedc91e1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BaselineImage item.
            /// </summary>
            [RepositoryItem("af8e4a4f-9239-4240-97df-aedb230a6e7f")]
            public virtual Ranorex.Picture BaselineImage
            {
                get
                {
                    return _baselineimageInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The BaselineImage item info.
            /// </summary>
            [RepositoryItemInfo("af8e4a4f-9239-4240-97df-aedb230a6e7f")]
            public virtual RepoItemInfo BaselineImageInfo
            {
                get
                {
                    return _baselineimageInfo;
                }
            }

            /// <summary>
            /// The ButtonOpen item.
            /// </summary>
            [RepositoryItem("733e6283-6084-46e4-9cf0-224195313091")]
            public virtual Ranorex.Button ButtonOpen
            {
                get
                {
                    return _buttonopenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOpen item info.
            /// </summary>
            [RepositoryItemInfo("733e6283-6084-46e4-9cf0-224195313091")]
            public virtual RepoItemInfo ButtonOpenInfo
            {
                get
                {
                    return _buttonopenInfo;
                }
            }
        }

        /// <summary>
        /// The ContactUsMyStoreGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("8f9b8f13-5444-4b6d-bb44-5c598cd41f42")]
        public partial class ContactUsMyStoreGoogleChromeAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ContactUsMyStoreGoogleChrome  folder.
            /// </summary>
            public ContactUsMyStoreGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ContactUsMyStoreGoogleChrome", "/form[@title>'Contact us - My Store - Google']", parentFolder, 30000, null, true, "8f9b8f13-5444-4b6d-bb44-5c598cd41f42", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8f9b8f13-5444-4b6d-bb44-5c598cd41f42")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8f9b8f13-5444-4b6d-bb44-5c598cd41f42")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
